language: python

python:
  - "2.7"
  - "3.6"

before_install:
  - pip install -U pip
  - python setup.py install
  
install:
  # make sure that we have a Qt backend installed
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install pyside;
    else
      pip install pyqt5;
    fi
  
  # also install requirements .txt
  - pip install -r requirements.txt
  
before_script:
  # From the travis docs: https://docs.travis-ci.com/user/gui-and-headless-browsers/
  # To run tests requiring a graphical user interface on Travis CI, use xvfb (X Virtual Framebuffer)
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  
script:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      py.test --doctest-modules;
    else
      pytest --doctest-modules;
    fi

after_success:
  - pip install python-coveralls
  - coveralls
