language: python

#virtualenv:
#  system_site_packages: true

python:
#  - "2.7"
  - "3.6"

before_install:
  - pip install -U pip
  - python setup.py install
  
install:
  # make sure that we have a Qt backend installed
  #- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
  #    pip install pyside;
  #  else
  #    pip install pyqt5;
  #  fi
  
  # Setup miniconda
  # https://github.com/pytest-dev/pytest-qt/blob/master/.travis.yml
  # https://github.com/astropy/ci-helpers
  - git clone --depth 1 git://github.com/astropy/ci-helpers.git
  - CONDA_DEPENDENCIES="${DEPS} ${PYQT_PACKAGE}" source ci-helpers/travis/setup_conda.sh
  - source activate test && pip install -e .
  - pip install pyqt5
  
  # also install requirements .txt
  - pip install -r requirements.txt
  
script:
  #- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
  #    py.test;
  #  else
  #    pytest;
  #  fi
  - pytest --doctest-modules

after_success:
  - coveralls
