language: python

python:
  - "2.7"
  - "3.6"
  
 virtualenv:
  system_site_packages: true
  
 before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3-pyqt5
  
install:
  - pip install -r requirements.txt
  
script: pytest