language: python

#virtualenv:
#  system_site_packages: true

python:
#  - "2.7"
  - "3.6"

before_install:
  - pip install -U pip
  - python setup.py install
  
install:
  # make sure that we have a Qt backend installed
  #- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
  #    pip install pyside;
  #  else
  #    pip install pyqt5;
  #  fi
  
  - pip install pyqt5
  
  # also install requirements .txt
  - pip install -r requirements.txt
  
script:
  #- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
  #    py.test;
  #  else
  #    pytest;
  #  fi
  - pytest --doctest-modules

after_success:
  - coveralls
