language: python

#virtualenv:
#  system_site_packages: true

python:
  - "2.7"
  - "3.6"

before_install:
  - pip install -U pip
  - python setup.py install
  
install:
  # Adopted from https://github.com/fchollet/keras/blob/master/.travis.yml.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
     fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  
  # make sure that pyqt is installed
  - pip install pyqt5
  
  # also install requirements .txt
  - pip install -r requirements.txt
  
script:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      py.test;
    else
      pytest;
    fi

after_success:
  - coveralls
